name    'dropbox-osx_ard'
version '0.1.0'
license 'Apache License, Version 2.0'
summary 'Apple Remote Desktop Module for OS X'
description 'Module for Configuring Apple Remote Desktop on OS X' 
dependency 'dropbox/osx_utils', '0.x'